### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by KangbaoShi** [barbarbar338/csgo-cheat-go#1]
So, how to use it? build exe?
think u.

**Comment by barbarbar338** [comment]
It's still WIP and has many bugs but if you want you can run it easly with command `go run .` don't forget to install golang first :) https://golang.org/

Also more descriptive docs will be added to the repo soon

**Comment by barbarbar338** [comment]
https://github.com/barbarbar338/csgo-cheat-go#readme
